In [4]:
import numpy as np
import torch

In [2]:
a = np.random.rand(4,3)
a

array([[0.74789385, 0.94906701, 0.06803213],
       [0.83796623, 0.68018628, 0.37699806],
       [0.96041724, 0.89426243, 0.05604998],
       [0.47303464, 0.6466603 , 0.31854804]])

In [5]:
b = torch.from_numpy(a)
b

tensor([[0.7479, 0.9491, 0.0680],
        [0.8380, 0.6802, 0.3770],
        [0.9604, 0.8943, 0.0560],
        [0.4730, 0.6467, 0.3185]], dtype=torch.float64)

In [6]:
b.numpy()


array([[0.74789385, 0.94906701, 0.06803213],
       [0.83796623, 0.68018628, 0.37699806],
       [0.96041724, 0.89426243, 0.05604998],
       [0.47303464, 0.6466603 , 0.31854804]])

In [7]:
#multiply pytorch tensor by 2 , in place
b.mul_(2)


tensor([[1.4958, 1.8981, 0.1361],
        [1.6759, 1.3604, 0.7540],
        [1.9208, 1.7885, 0.1121],
        [0.9461, 1.2933, 0.6371]], dtype=torch.float64)

In [8]:
a

array([[1.49578771, 1.89813401, 0.13606425],
       [1.67593246, 1.36037255, 0.75399612],
       [1.92083449, 1.78852486, 0.11209997],
       [0.94606929, 1.29332059, 0.63709609]])